#!/usr/bin/env python3
"""Crop a full-canvas faceplate overlay to its ink and emit its geometry.

The faceplate overlays (variant badges, the engraved CLOUD label) are authored
as full-canvas 5480x4680 transparent PNGs so they register with the plate
exactly, with no position to measure by hand. Shipping them that way is very
expensive: the system decodes an overlay at full resolution regardless of how
little of it is ink, costing ~98 MB of resident memory EACH (measured: removing
one full-canvas overlay dropped the app's RSS from 350 MB to 242 MB).

So: keep authoring full-canvas, but ship cropped. This crops an overlay to its
ink bounds and prints the Swift geometry to place it back in exactly the same
spot, in base-design points (the 504x430 design that FaceplateDesign.scale
multiplies).

Usage:
    python3 tools/crop-overlay.py <in.png> [more.png ...] [--out DIR] [--union]

--union crops every input to their combined bounds, so variants of the same
artwork (e.g. the red and blue badges) share one set of constants.
"""
import argparse, os, sys
from PIL import Image

BASE_W, BASE_H = 504.0, 430.0   # base-design window, scale 1.0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("inputs", nargs="+")
    ap.add_argument("--out", default=None, help="output dir (default: alongside input)")
    ap.add_argument("--union", action="store_true", help="crop all inputs to shared bounds")
    a = ap.parse_args()

    imgs = [(p, Image.open(p).convert("RGBA")) for p in a.inputs]

    canvas = {im.size for _, im in imgs}
    if len(canvas) != 1:
        print(f"error: inputs differ in canvas size: {canvas}", file=sys.stderr)
        return 1
    cw, ch = canvas.pop()

    boxes = []
    for p, im in imgs:
        b = im.getchannel("A").getbbox()      # alpha > 0, so no antialiasing is clipped
        if b is None:
            print(f"error: {p} is fully transparent", file=sys.stderr)
            return 1
        boxes.append(b)

    if a.union or len(imgs) > 1:
        box = (min(b[0] for b in boxes), min(b[1] for b in boxes),
               max(b[2] for b in boxes), max(b[3] for b in boxes))
    else:
        box = boxes[0]

    x0, y0, x1, y1 = box
    w_pt = (x1 - x0) * BASE_W / cw
    h_pt = (y1 - y0) * BASE_H / ch
    cx_pt = (x0 + x1) / 2 * BASE_W / cw
    cy_pt = (y0 + y1) / 2 * BASE_H / ch

    for p, im in imgs:
        crop = im.crop(box)
        dest = os.path.join(a.out, os.path.basename(p)) if a.out else p
        crop.save(dest, optimize=True)
        before = cw * ch * 4 / 1024 / 1024
        after = crop.size[0] * crop.size[1] * 4 / 1024 / 1024
        print(f"{os.path.basename(p)}: {cw}x{ch} -> {crop.size[0]}x{crop.size[1]}"
              f"   decoded {before:.0f} MB -> {after:.1f} MB", file=sys.stderr)

    print(f"\n// generated by tools/crop-overlay.py — base-design points", file=sys.stderr)
    print(f"static let size = CGSize(width: s({w_pt:.2f}), height: s({h_pt:.2f}))")
    print(f"static let position = CGPoint(x: s({cx_pt:.2f}), y: s({cy_pt:.2f}))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
